# Build HTML and man pages, put the man pages underneath html/man/ so they
# get served as well.
[build]
  command = "make html && make man && mv _build/man _build/html"
  publish = "_build/html"

# PDF artifacts are transparently proxied to the old server
[[redirects]]
  from = "/pdf/*"
  to = "https://web.syncthing.net/docs-pdf/:splat"
  status = 200

# Branches are served from the old webserver
[[redirects]]
  from = "/branch/*"
  to = "https://web.syncthing.net/docs-branch/:splat"
  status = 200
