name: Refresh version list
on:
  workflow_dispatch:
  schedule:
    # Wednesday mornings
    - cron:  '42 7 * * 3'


jobs:

  refresh-versions:
    runs-on: ubuntu-latest
    name: Refresh versions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Run refresh script
        run: |
          set -euo pipefail
          bash refresh-versions.sh
          if [ -z "$(git status --porcelain)" ]; then exit 0; fi
          git config --global user.name 'Syncthing Release Automation'
          git config --global user.email 'release@syncthing.net'
          git commit -am 'Update version list'
          git push
